### ISSUE TITLE
problem with granting resources

### ISSUE THREAD

**Issue by everythinginjs** [johnyvelho/admin-bro-users-permissions#1]
hello @johnyvelho  thanks for setting up this great feature for admin-bro. I could set up successfully but the problem that I have got is when I grant a resource to a user and login with that user nothing changes except the granted resource returns error like this in terminal 
Error: There are no resources with given id: "Admin"
[💻] This is the list of all registered resources you can use:
[💻] Customer, Product, Blog, BlogCat, BlogTag, ProductCat, ProductSubCat, User, Role

this is my actions 

```
actions: {
    list: {
      isAccessible: isAccessGranted({
        resourceName: 'Blog',
        actionRequested: 'list',
      }),
    },
    edit: {
      isAccessible: isAccessGranted({
        resourceName: 'Blog',
        actionRequested: 'edit',
      }),
    },
    new: {
      isAccessible: isAccessGranted({
        resourceName: 'Blog',
        actionRequested: 'new',
      }),
    },
    bulkDelete: {
      isAccessible: isAccessGranted({
        resourceName: 'Blog',
        actionRequested: 'bulkDelete',
      }),
    },
    delete: {
      isAccessible: isAccessGranted({
        resourceName: 'Blog',
        actionRequested: 'delete',
      }),
    },
    search: {
      isAccessible: isAccessGranted({
        resourceName: 'Blog',
        actionRequested: 'search',
      }),
    },
    show: {
      isAccessible: isAccessGranted({
        resourceName: 'Blog',
        actionRequested: 'show',
      }),
    },
  },
```

would be appreciated for any assistance,

**Comment by johnyvelho** [comment]
hey @Amixengineer. just to be sure, what version are you using?
Also, is there any possibility for me to check your entire repository/run it locally?

**Comment by johnyvelho** [comment]
Hi @Amixengineer , thanks for giving me access to your repository.
After a quick look, I could identify that this is not working because it's not configured correctly. All your resources actions are using the same resourceName: Blog

`
isAccessible: isAccessGranted({
        resourceName: 'Blog',
        actionRequested: 'list',
      })
`

Since your role permits access to Blog resource and all your resources are configured to resourceName: Blog, all of them will be accessible for this role.
You just have to change your resourceName for the correct one. If it is product resource, change it to Product. if its Task, change it to Task, etc.

**Comment by everythinginjs** [comment]
Thanks Johny for setting aside time to look into the repo, yes I started copying `isAccessible: isAccessGranted({ resourceName: 'Blog', actionRequested: 'list', })` to all resources :)) since I was tried of working too much then I faced that problem, but to make it clear for the ones are reading this issue of mine. I handled author names for blog posts by making a relation between my ex-Admin and Blog resource like this `Schema.Types.ObjectId` with the reference of 'admin' in the Blog Model, and then got familiar with your amazing solution, and I forgot to change ref value to 'User' model, because of this I got this error when I wanted to open Blog resource of adminBro panel.

thanks for your great support, love you,
