### ISSUE TITLE
Admin bro rebranded to admin js 

### ISSUE THREAD

**Issue by everythinginjs** [johnyvelho/admin-bro-users-permissions#4]
Hellllllo Johny i can see you use @admin-bro/passwords in your package please change admin-bro to adminjs thanks 🙏

**Comment by everythinginjs** [comment]
If you are busy I can make a PR ! BTW,

**Comment by johnyvelho** [comment]
heeey @Amixengineer I've no time to work on it now :( but I invited you as a collaborator, so feel free to open your PR and work on it
